/*
 * Restler API Explorer
 *
 * Live API Documentation
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// OutputAddressInfo Model
    /// </summary>
    [DataContract]
    public partial class OutputAddressInfo : IEquatable<OutputAddressInfo>
    { 
        /// <summary>
        /// the output address, in a form that would be recognizable to the output wallet. This might be an address, a public key, an account name, or account number.
        /// </summary>
        /// <value>the output address, in a form that would be recognizable to the output wallet. This might be an address, a public key, an account name, or account number.</value>
        [Required]
        [DataMember(Name="address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or Sets Memo
        /// </summary>
        [Required]
        [DataMember(Name="memo")]
        public string Memo { get; set; }

        /// <summary>
        /// the nickname the user assigned when creating this output address If the user didn&#39;t create a nickname, BlockTrades automatically generates one.
        /// </summary>
        /// <value>the nickname the user assigned when creating this output address If the user didn&#39;t create a nickname, BlockTrades automatically generates one.</value>
        [Required]
        [DataMember(Name="nickname")]
        public string Nickname { get; set; }

        /// <summary>
        /// the wallet type for this output address
        /// </summary>
        /// <value>the wallet type for this output address</value>
        [Required]
        [DataMember(Name="walletType")]
        public string WalletType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OutputAddressInfo {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Memo: ").Append(Memo).Append("\n");
            sb.Append("  Nickname: ").Append(Nickname).Append("\n");
            sb.Append("  WalletType: ").Append(WalletType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((OutputAddressInfo)obj);
        }

        /// <summary>
        /// Returns true if OutputAddressInfo instances are equal
        /// </summary>
        /// <param name="other">Instance of OutputAddressInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OutputAddressInfo other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Address == other.Address ||
                    Address != null &&
                    Address.Equals(other.Address)
                ) && 
                (
                    Memo == other.Memo ||
                    Memo != null &&
                    Memo.Equals(other.Memo)
                ) && 
                (
                    Nickname == other.Nickname ||
                    Nickname != null &&
                    Nickname.Equals(other.Nickname)
                ) && 
                (
                    WalletType == other.WalletType ||
                    WalletType != null &&
                    WalletType.Equals(other.WalletType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Address != null)
                    hashCode = hashCode * 59 + Address.GetHashCode();
                    if (Memo != null)
                    hashCode = hashCode * 59 + Memo.GetHashCode();
                    if (Nickname != null)
                    hashCode = hashCode * 59 + Nickname.GetHashCode();
                    if (WalletType != null)
                    hashCode = hashCode * 59 + WalletType.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(OutputAddressInfo left, OutputAddressInfo right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(OutputAddressInfo left, OutputAddressInfo right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
