/*
 * Restler API Explorer
 *
 * Live API Documentation
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// UsersModel2 Model
    /// </summary>
    [DataContract]
    public partial class UsersModel2 : IEquatable<UsersModel2>
    { 
        /// <summary>
        /// the number sent to the user by email to validate that they own the address
        /// </summary>
        /// <value>the number sent to the user by email to validate that they own the address</value>
        [Required]
        [DataMember(Name="validationId")]
        public string ValidationId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UsersModel2 {\n");
            sb.Append("  ValidationId: ").Append(ValidationId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UsersModel2)obj);
        }

        /// <summary>
        /// Returns true if UsersModel2 instances are equal
        /// </summary>
        /// <param name="other">Instance of UsersModel2 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UsersModel2 other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ValidationId == other.ValidationId ||
                    ValidationId != null &&
                    ValidationId.Equals(other.ValidationId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ValidationId != null)
                    hashCode = hashCode * 59 + ValidationId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UsersModel2 left, UsersModel2 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UsersModel2 left, UsersModel2 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
