/*
 * LedgerLocal Server API
 *
 * LedgerLocal Server API swagger-2.0 specification
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace LedgerLocal.AdminServer.Api.Web.Models
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CustomerCreateOrUpdate
    {
        public CustomerCreateOrUpdate()
        {           
        }

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>
        [DataMember(Name="customerId")]
        public string CustomerId { get; set; }

        /// <summary>
        /// Gets or Sets GodFatherId
        /// </summary>
        [DataMember(Name = "godFatherId")]
        public string GodFatherId { get; set; }

        /// <summary>
        /// Gets or Sets Salutation
        /// </summary>
        [DataMember(Name="salutation")]
        public string Salutation { get; set; }
        /// <summary>
        /// First name of the LedgerLocal user.
        /// </summary>
        /// <value>First name of the LedgerLocal user.</value>
        [DataMember(Name="firstName")]
        public string FirstName { get; set; }
        /// <summary>
        /// Last name of the LedgerLocal user.
        /// </summary>
        /// <value>Last name of the LedgerLocal user.</value>
        [DataMember(Name="lastName")]
        public string LastName { get; set; }
        /// <summary>
        /// Email address of the LedgerLocal user
        /// </summary>
        /// <value>Email address of the LedgerLocal user</value>
        [DataMember(Name="email")]
        public string Email { get; set; }
        /// <summary>
        /// Image URL of the LedgerLocal user.
        /// </summary>
        /// <value>Image URL of the LedgerLocal user.</value>
        [DataMember(Name="picture")]
        public string Picture { get; set; }

        [DataMember(Name = "phone")]
        public string Phone { get; set; }

        [DataMember(Name = "birthday")]
        public DateTime? Birthday { get; set; }
    }
}
