/*
 * LedgerLocal Server API
 *
 * LedgerLocal Server API swagger-2.0 specification
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace LedgerLocal.FrontServer.Api.Web.Models
{

    [DataContract]
    public partial class WorkflowExecutionWithArgs
    {

        [DataMember(Name="workflowId")]
        public string WorkflowId { get; set; }

        [DataMember(Name = "LedgerLocalJsContent")]
        public string LedgerLocalJsContent { get; set; }

        [DataMember(Name = "timeout")]
        public Int32 Timeout { get; set; }

        [DataMember(Name = "dicoArgs")]
        public IDictionary<string, object> DicoArgs { get; set; }

        [DataMember(Name = "debug")]
        public bool Debug { get; set; }

    }
}
