/*
 * LoyaltyCoin Server API
 *
 * LoyaltyCoin Server API swagger-2.0 specification
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace LedgerLocal.Dto.Chain
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AssetCreateOrUpdate
    {

        public AssetCreateOrUpdate()
        {
                        
        }

        /// <summary>
        /// Gets or Sets AssetLabel
        /// </summary>
        [DataMember(Name="assetLabel")]
        public string AssetLabel { get; set; }
        /// <summary>
        /// Gets or Sets AssetSymbol
        /// </summary>
        [DataMember(Name="assetSymbol")]
        public string AssetSymbol { get; set; }
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name")]
        public string Name { get; set; }
        
    }
}
